# Generated by Django 4.2.13 on 2024-06-14 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_alter_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('acts', 'Акты'), ('orders', 'Приказы'), ('document_package', 'Пакет документов')], max_length=20)),
                ('organization_name', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=12)),
                ('ogrn', models.CharField(max_length=13)),
                ('responsible_person', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
