# Generated by Django 4.2.13 on 2024-06-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_generateddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='address',
            field=models.CharField(default='Не указано', max_length=255),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='position',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
